### ISSUE TITLE
getting vision api key is invlaid

### ISSUE THREAD

**Issue by xts-princyv** [brminnick/XamSpeak#5]

**Comment by xts-princyv** [comment]
when am providing vision api key it throws api key is invalid

**Comment by TheCodeTraveler** [comment]
There is a breaking change in Microsoft.Azure.CognitiveServices.Vision.ComputerVision v3.2.0 that requires the BaseUrl. XamSpeak was using v2.1.0.

Updated all NuGet Packages and added CognitiveServicesConstants.ComputerVisionBaseUrl as a required input.
